= Spring Boot Camel SOAP to REST bridge QuickStart

This example demonstrates how to use Camel's REST DSL to expose a backend SOAP API.

===  Mainly purpose of this quickstart
1. A simple camel route can brige REST invocation to legacy SOAP service.
2. Security is involved for both REST endpoint and SOAP enpoint, both backed by RH SSO. Frontend REST API protected via OAuth and OpenID Connect, and the client will fetch JWT access token from RH SSO using https://tools.ietf.org/html/rfc6749#section-4.3["Resource Owner Password Credentials"] OAuth2 mode and using this token to access the REST endpoint. In the bridge camel route, client identity is propaged from SecurityContext and when camel-cxf producer talk to the backend WS-SECURITY protected SOAP service, it will firstly using this client identity to fetch a SAML2 token issued by CXF STS service(which is backed by RH SSO as Identity Provider), and the SAML2 token is signed and put in WS-SECURITY header, and the backend WS-SECURITY protected SOAP service will validate this SAML2 token accordingly. The SOAP invocation also includes XSD Schema Validation. If the token validation is successful, the backend SOAP service will return response and the response will return to the REST client which initially sends out the request.

This example relies on the https://maven.fabric8.io[Fabric8 Maven plugin] for its build configuration
and uses the https://github.com/fabric8io/base-images#java-base-images[fabric8 Java base image].

The application utilizes the Spring http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ImportResource.html[`@ImportResource`] annotation to load a Camel Context definition via a _src/main/resources/spring/camel-context.xml_ file on the classpath.

IMPORTANT: This quickstart can run in 2 modes: standalone on your machine and on Kubernetes / OpenShift Cluster.

* When running in standalone mode, a standalone RH SSO instance must be installed, started and configured properly on the local machine. Since there is no standalone 3Scale avaiable, the standalone mode doesn't involve 3Scale.
* When running in Openshift Cluster, the RH SSO and 3Scale images must be installed, started and configured properly on the openshift.

== Deployment options

You can run this quickstart in the following modes:

* Kubernetese / Single-node OpenShift cluster
* Standalone on your machine

The most effective way to run this quickstart is to deploy and run the project on OpenShift.

For more details about running this quickstart on a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

== Running the Quickstart on a single-node Kubernetes/OpenShift cluster

IMPORTANT: You need to run this example on OpenShift 3.11, RH SSO 7.4 and 3Scale 2.8.

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

In this quickstart, we will give detailed steps to run it on a local installed minishift.

. Start minishift 
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift start --memory 8GB --cpus 4
----
Since we need to install RH SSO image(2 pods) and 3Scale image(15 pods) as pre-requirement, so we need start minishift on a powerful machine, with options "--memory 8GB --cpus 4"

. Set timezone on openshift cluster
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ minishift timezone --set America/Toronto
----
Since in this quickstart, we need to issue security token, so the timezone matters because security token has expiration time. Ensure the openshift cluster uses the same time zone as your local machine(By default it will use UTC timezone)

. Add cluster-admin role to user developer
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u system:admin
$ oc adm policy add-cluster-role-to-user cluster-admin developer
$ oc login -u developer
$ oc project openshift
----
We will install this quickstart in openshift project|namespace(this is also expected by default configurations of the templates involved), as well as the RH SSO image, so we need to add cluster-admin role to user developer.

. Create secret and link it to serviceaccounts
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc create secret docker-registry camel-bridge --docker-server=registry.redhat.io \
  --docker-username=USERNAME \
  --docker-password=PASSWORD \
  --docker-email=EMAIL_ADDRESS
$ oc secrets link default camel-bridge --for=pull
$ oc secrets link builder camel-bridge
----
Since Openshift 3.11, the new default docker image server registry.redhat.io requires authentication. To be able to access registry.redhat.io, users need to create USERNAME and PASSWORD https://access.redhat.com/terms-based-registry/[here].
More details can be found https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/configuring_clusters/install-config-configuring-red-hat-registry[here], the ***6.1.2. Creating Service Accounts and Authentication Tokens for the Red Hat Registry*

. Add RH SSO image stream and install RH SSO with template "sso74-x509-postgresql-persistent"
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ for resource in sso74-image-stream.json \
   sso74-https.json \
   sso74-postgresql.json \
   sso74-postgresql-persistent.json \
   sso74-x509-https.json \
   sso74-x509-postgresql-persistent.json
 do
   oc create -f \
   https://raw.githubusercontent.com/jboss-container-images/redhat-sso-7-openshift-image/sso74-dev/templates/${resource}
 done

$ oc policy add-role-to-user view system:serviceaccount:$(oc project -q):default

$ oc new-app --template=sso74-x509-postgresql-persistent
----
Firstly ensure RH SSO images are available from openshift namespace, and then install RH SSO with template "sso74-x509-postgresql-persistent". This template can save all RH SSO configuration permenantly, so the configuration won't get lost after openshift restart.

. Add RH FUSE image stream into openshift namespace
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ BASEURL=https://raw.githubusercontent.com/jboss-fuse/application-templates/application-templates-2.1.0.fuse-760043-redhat-00001

$ oc create  -f ${BASEURL}/fis-image-streams.json
----
This step will make FUSE related images available in openshift namespace.

. Install 3scale in 3scale namespace|project
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project 3scale
$ oc create secret docker-registry threescale-registry-auth --docker-server=registry.redhat.io --docker-server=registry.redhat.io \
  --docker-username=USERNAME \
  --docker-password=PASSWORD \
  --docker-email=EMAIL_ADDRESS
$ oc secrets link default threescale-registry-auth --for=pull
$ oc secrets link builder threescale-registry-auth
$ oc new-app    --param WILDCARD_DOMAIN="$(minishift ip).nip.io"       -f https://raw.githubusercontent.com/3scale/3scale-amp-openshift-templates/2.8.0.GA/amp/amp-eval-tech-preview.yml
----
3scale installation on openshift will start 15 pods, so we create a new specific namespace|project for 3scale. Also we need a new threescale-registry-auth(this name matters since it's written in 3scale templates) secret for 3scale(we can reuse the USERNAME/PASSWORD from camel-bridge secret).  We intentionally use amp-eval-tech-preview.yml template here cause it doesn't explicitly specify hardware resources so can be easily run a local machine/laptop.

. Configure RH SSO: (TBD)
. Configure 3Scale API Gateway(TBD)

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/spring-boot-camel-soap-rest-bridge`) :
+
or
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/spring-boot-camel-soap-rest-bridge
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean fabric8:deploy -Popenshift -DJAVA_OPTIONS="-Dsso.server=https://sso-openshift.192.168.64.33.nip.io -Dweather.service.host=192.168.0.11"
----
We need to pass in two properties to camel-soap-rest-bridge image on openshift. One is the RH SSO server address on openshift, and this is
https://sso-openshift.$(minishift ip).nip.io. Another one is the backend soap server, in this quickstart, we run the backend soap server on the local machine, so pass the local ip address of your machine as -Dweather.service.host.( must be an ip address other than localhost or 127.0.0.1)

. Run the test
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean  test -Dtest=IntegrationTest -Dsso.server=https://sso-openshift.192.168.64.33.nip.io -Dcamel.route.host=https://api-3scale-apicast-production.192.168.64.33.nip.io:443 -D3scale.user.key=9f37d93b27f7b552f30116919cc59048
----
We need to pass in three properties to run test
1. sso.servder: RH SSO server address on openshift, this is https://sso-openshift.$(minishift ip).nip.io
2. camel.route.host: this is the address from which runs camel route. Since on openshift, we need use 3scale as API gateway, so this is https://api-3scale-apicast-production.$(minishift ip).nip.io
3. 3scale.user.key: this is the user key we use to access 3scale API gateway, we can get it when configuring 3scale

. Insight of the test
1. This test will start a backend SOAP service, which is protected by WS-Security Timestamp and Signed SAML2 token(need elaboration)
2. This test contains 5 test cases, demonstrates 5 different scenarios
   - testJavaClient: this testcase won't go through camel route, instead, it's a simple JAXWS API client which sends request to backend SOAP service, but without required WS-SECURITY headers, hence an exception is expected.
   - testRestClientWithSTS: this testcase is the most normal one which tests the whole flow of the quickstart. It contains several steps
       - fetch an access token from the RH SSO. Here we use the "Resource Owner Password Credentials Grant" OAuth2 flow, which is no UI interaction involved and suitable for Java code based client/server request/response invocation.
       -
   
   - testRestClientWithIncorrectToken(elaboration)
   - testRestClientWithSTSInvalidZipCode(elaboration)
   - testRestClientWithInvalidPayload:

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `spring-boot-camel-rest-3scale` has started up.

. On the project's `Overview` page, navigate to the details page deployment of the `spring-boot-camel-rest-3scale` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/pods/spring-boot-camel-rest-3scale-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the log from Camel.

[#single-node-without-preinstalled-images]
=== Running the Quickstart on a single-node Kubernetes/OpenShift cluster without preinstalled images

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.


. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Import base images in your newly created project (MY_PROJECT_NAME):
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc import-image fis-java-openshift:2.0 --from=registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0 --confirm
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/spring-boot-camel-rest-3scale`) :
+
or
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/spring-boot-camel-rest-3scale
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift  -Dfabric8.generator.fromMode=istag -Dfabric8.generator.from=MY_PROJECT_NAME/fis-java-openshift:2.0
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `spring-boot-camel-rest-3scale` has started up.

. On the project's `Overview` page, navigate to the details page deployment of the `spring-boot-camel-rest-3scale` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/pods/spring-boot-camel-rest-3scale-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the log from Camel.

== Accessing the REST service

When the example is running, a REST service is available to list users that have called this service. The user information comes from 3scale extensions to autofill API keys. 

* `"x-data-threescale-name": "app_ids"` for the parameter that represents the application ID.
* `"x-data-threescale-name": "app_keys"` or `"x-data-threescale-name": "user_keys"` for the parameter that represents the application or user key.

Notice: As it depends on your OpenShift setup, the hostname (route) might vary. Verify with `oc get routes` which hostname is valid for you.

The actual endpoint is using the _context-path_ `camel-rest-3scale/users` and the REST service provides two services:

- `users/greet`: to use 3scale API keys to add a user to this service's list of calling users
- `users/list`: to list all users that have called the service

You can then access these services from your Web browser, e.g.:

- <http://spring-boot-camel-rest-3scale-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io/camel-rest-3scale/users/greet>
- <http://spring-boot-camel-rest-3scale-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io/camel-rest-3scale/users/list>

== Swagger API

The example provides API documentation of the service using Swagger using the _context-path_ `camel-rest-3scale/api-doc`. You can access the API documentation from your Web browser at <http://spring-boot-camel-rest-3scale-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io/camel-rest-3scale/api-doc>.

== Running the quickstart standalone on your machine

To run this quickstart as a standalone project on your local machine:

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. Run the service:

+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn spring-boot:run
----
+
Alternatively, you can run the application locally using the executable JAR produced:
+
----
$ java -jar -Dspring.profiles.active=dev target/spring-boot-camel-rest-3scale-1.0-SNAPSHOT.jar
----

. You can then access the REST API directly from your Web browser, e.g.:

- <http://localhost:8080/camel-rest-3scale/users/greet>
- <http://localhost:8080/camel-rest-3scale/users/list>



