= Spring Boot Camel SOAP to REST bridge QuickStart

This example demonstrates how to use Camel's REST DSL to expose a backend SOAP API.

===  Mainly purpose of this quickstart
1. A simple camel route can brige REST invocation to legacy SOAP service.
2. Security is involved for both REST endpoint and SOAP enpoint, both backed by RH SSO. Frontend REST API protected via OAuth and OpenID Connect, and the client will fetch JWT access token from RH SSO using https://tools.ietf.org/html/rfc6749#section-4.3["Resource Owner Password Credentials"] OAuth2 mode and using this token to access the REST endpoint. In the bridge camel route, client identity is propaged from SecurityContext and when camel-cxf producer talk to the backend WS-SECURITY protected SOAP service, it will firstly using this client identity to fetch a SAML2 token issued by CXF STS service(which is backed by RH SSO as Identity Provider), and the SAML2 token is signed and put in WS-SECURITY header, and the backend WS-SECURITY protected SOAP service will validate this SAML2 token accordingly. The SOAP invocation also includes XSD Schema Validation. If the token validation is successful, the backend SOAP service will return response and the response will return to the REST client which initially sends out the request.

This example relies on the https://maven.fabric8.io[Fabric8 Maven plugin] for its build configuration
and uses the https://github.com/fabric8io/base-images#java-base-images[fabric8 Java base image].

The application utilizes the Spring http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ImportResource.html[`@ImportResource`] annotation to load a Camel Context definition via a _src/main/resources/spring/camel-context.xml_ file on the classpath.

IMPORTANT: This quickstart can run in 2 modes: standalone on your machine and on Kubernetes / OpenShift Cluster.

* When running in standalone mode, a standalone RH SSO instance must be installed, started and configured properly on the local machine. Since there is no standalone 3Scale avaiable, the standalone mode doesn't involve 3Scale.
* When running in Openshift Cluster, the RH SSO and 3Scale images must be installed, started and configured properly on the openshift.

== Deployment options

You can run this quickstart in the following modes:

* Kubernetese / Single-node OpenShift cluster
* Standalone on your machine

The most effective way to run this quickstart is to deploy and run the project on OpenShift.

For more details about running this quickstart on a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

== Running the Quickstart on a single-node Kubernetes/OpenShift cluster

IMPORTANT: You need to run this example on OpenShift 3.11, RH SSO 7.4 and 3Scale 2.8.

If you run it in an environment where those images are not preinstalled follow the steps described in <<single-node-without-preinstalled-images>>.

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/spring-boot-camel-rest-3scale`) :
+
or
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/spring-boot-camel-rest-3scale
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `spring-boot-camel-rest-3scale` has started up.

. On the project's `Overview` page, navigate to the details page deployment of the `spring-boot-camel-rest-3scale` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/pods/spring-boot-camel-rest-3scale-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the log from Camel.

[#single-node-without-preinstalled-images]
=== Running the Quickstart on a single-node Kubernetes/OpenShift cluster without preinstalled images

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.


. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Import base images in your newly created project (MY_PROJECT_NAME):
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc import-image fis-java-openshift:2.0 --from=registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0 --confirm
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/spring-boot-camel-rest-3scale`) :
+
or
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/spring-boot-camel-rest-3scale
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift  -Dfabric8.generator.fromMode=istag -Dfabric8.generator.from=MY_PROJECT_NAME/fis-java-openshift:2.0
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `spring-boot-camel-rest-3scale` has started up.

. On the project's `Overview` page, navigate to the details page deployment of the `spring-boot-camel-rest-3scale` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/pods/spring-boot-camel-rest-3scale-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the log from Camel.

== Accessing the REST service

When the example is running, a REST service is available to list users that have called this service. The user information comes from 3scale extensions to autofill API keys. 

* `"x-data-threescale-name": "app_ids"` for the parameter that represents the application ID.
* `"x-data-threescale-name": "app_keys"` or `"x-data-threescale-name": "user_keys"` for the parameter that represents the application or user key.

Notice: As it depends on your OpenShift setup, the hostname (route) might vary. Verify with `oc get routes` which hostname is valid for you.

The actual endpoint is using the _context-path_ `camel-rest-3scale/users` and the REST service provides two services:

- `users/greet`: to use 3scale API keys to add a user to this service's list of calling users
- `users/list`: to list all users that have called the service

You can then access these services from your Web browser, e.g.:

- <http://spring-boot-camel-rest-3scale-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io/camel-rest-3scale/users/greet>
- <http://spring-boot-camel-rest-3scale-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io/camel-rest-3scale/users/list>

== Swagger API

The example provides API documentation of the service using Swagger using the _context-path_ `camel-rest-3scale/api-doc`. You can access the API documentation from your Web browser at <http://spring-boot-camel-rest-3scale-MY_PROJECT_NAME.OPENSHIFT_IP_ADDR.nip.io/camel-rest-3scale/api-doc>.

== Running the quickstart standalone on your machine

To run this quickstart as a standalone project on your local machine:

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. Run the service:

+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn spring-boot:run
----
+
Alternatively, you can run the application locally using the executable JAR produced:
+
----
$ java -jar -Dspring.profiles.active=dev target/spring-boot-camel-rest-3scale-1.0-SNAPSHOT.jar
----

. You can then access the REST API directly from your Web browser, e.g.:

- <http://localhost:8080/camel-rest-3scale/users/greet>
- <http://localhost:8080/camel-rest-3scale/users/list>



