package com.ibm.wdata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-sb2-740016-redhat-00001
 * 2020-03-31T10:31:59.307-04:00
 * Generated source version: 3.2.7.fuse-sb2-740016-redhat-00001
 *
 */
@WebService(targetNamespace = "http://ibm.com/wdata", name = "WeatherPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WeatherPortType {

    @WebMethod
    @WebResult(name = "WeatherResponse", targetNamespace = "http://ibm.com/wdata", partName = "weatherResponse")
    public WeatherResponse weatherRequest(
        @WebParam(partName = "weatherRequest", name = "WeatherRequest", targetNamespace = "http://ibm.com/wdata")
        WeatherRequest weatherRequest
    );
}
